<?php

function groceries_menu()
{
    $items = array();
    $items['groceries'] = array(
        'title' => "Groceries",
        'page callback' => 'groceries_display',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function groceries_display() {
    $grocery_list = array();
    $grocery_list['eggs'] = array(
        'price' => 1.99,
        'quantity' => 2
    );
    $grocery_list['milk'] = array(
        'price' => 2.49,
        'quantity' => 3
    );
    $grocery_list['apples'] = array(
        'price' => 0.5,
        'quantity' => 4
    );
    $output = '';
    $total_price = 0;

    foreach($grocery_list as $item_to_buy => $value) {

        $output .= '<ul><li><b>' . $item_to_buy . '</b>: $' . $value['price']*$value['quantity'] . '</li></ul>';
    }

    foreach($grocery_list as $item_to_buy) {
        $total_price += $item_to_buy['price'] * $item_to_buy['quantity'];
    }
    return $output . '<p> Total: $' . $total_price . '</p>';

}
